docker env fixes
maxpowa/npomf pull request #20
Opened 2017-01-31 13:20 UTC by GottZ

make docker configuration great again

`NPOMF_CONTACTS = ["foo@bar.com", "bar@foo.com"]` etc.

before it was impossible to assign arrays / objects through environment variables.

2017-02-05 19:43 UTC, GottZ commented
@maxpowa I'll create my own fork if you don't react :D

2017-02-05 20:06 UTC, RX14 commented
@GottZ maxpowa hasn't been on IRC since Friday. I'm sure he'll get to your PR if you're patient.

2017-02-06 15:47 UTC, maxpowa requested changes

2017-02-06 15:47 UTC, maxpowa commented on config/core.js
> +if (typeof config.DESCRIPTION == 'undefined') {
I prefer `=== undefined` rather than `typeof == 'undefined'`, probably best to check null as well.

2017-02-06 15:47 UTC, maxpowa commented on config/core.js
> +if (typeof config.UPLOAD_URL == 'undefined') config.UPLOAD_URL = config.URL;
ditto

2017-02-08 11:06 UTC, GottZ reviewed
i came up with an even better idea. will edit my pull request acordingly. you'll like it.

2017-02-08 16:41 UTC, merged

2017-02-08 16:41 UTC, maxpowa commented
LGTM, thanks.

2017-02-08 16:54 UTC, GottZ commented
lol I just noticed this would not work. it needs to be negated like if(!(foo in bar))

2017-02-08 16:55 UTC, maxpowa commented
Yup that's correct, this is what I get for code reviewing in the morning. I'll fix it.